### ISSUE TITLE
Add sequence cluster information to the website

### ISSUE THREAD

**Issue by lukasjelonek** [jhahnfeld/sorfdb-web#5]
The sequences have been clustered and now the cluster data has to be integrated to the website.

The website should have a new page that lists all cluster. For each cluster a separate page should exist that shows the cluster name and some statistics for the cluster: sequence-count, average sequence length, taxonomic profile. Furthermore it should show the function of the cluster (result of a majority vote of function from the sequences), multiple sequence alignment for all sequences of the cluster. It should show a list of all contained entries and it should be possible to jump to the entry details pages.

Currently available: 
* tsv file with protein sequence and clusterid
* folder with multiple alignments

**Comment by lukasjelonek** [comment]
Tasks:

- [ ] Add cluster id to all entries that are part of a cluster
- [ ] Compute statistics and function for each cluster and cache them somewhere (probably in a new index)
- [ ] Add list clusters page
- [ ] Add show cluster details page
- [ ] Add search to list clusters page (by taxonomic profile entries, sequence count, average sequence length, function)

Technical tasks:
- [ ] Add cluster-id to mapping for entries
- [ ] Add cluster index with appropriate mapping to server
- [ ] Add cluster endpoints to server
  - [ ] `POST /clusters/search`
  - [ ] `GET /clusters/:id`
  - [ ] `GET /clusters/:id/msa`

**Comment by lukasjelonek** [comment]
We decided that:

* the taxonomic profile is stored as a flat tree structure (see code)
* MSAs are stored in the cluster documents as a fasta string

**Comment by lukasjelonek** [comment]
Cluster type definition is available at: [src/model/Cluster.ts](https://github.com/jhahnfeld/sorfdb-web/blob/65ed82518f75c9cbf3995d347fecf69a2b422052/src/model/Cluster.ts)

**Comment by jhahnfeld** [comment]
Cluster allowed search types:

- id (String): Exakte Suche, Case insensitive
- sequenceCount (Integer): Exakte Suche
- averageSequenceLength (Float): Exakte Suche
- MedianSequenceLength (Integer): Exakte Suche
- function (String): Exakte Suche, Case insensitive, Volltextsuche

**Comment by lukasjelonek** [comment]
Should it be possible to search for the taxonomy labels?

**Comment by jhahnfeld** [comment]
Yes. I added it above.

**Comment by jhahnfeld** [comment]
Computed cluster statistics

[sorfdb.1.0.clusterStatistic.tar.gz](https://github.com/jhahnfeld/sorfdb-web/files/14416445/sorfdb.1.0.clusterStatistic.tar.gz)

**Comment by jhahnfeld** [comment]
Closed with [#1dfb4fa](https://github.com/jhahnfeld/sorfdb-web/commit/1dfb4fafa2fdc5198f7056fed8555aadb116ca45)
